### ISSUE TITLE
revision hash adding extra "g"

### ISSUE THREAD

**Issue by mehulkar** [pypa/setuptools-scm#152]
Hello! I've just discovered this project, and I'm seeing something that doesn't make sense (I'm most likely just doing something wrong, but don't know where else to ask the question). 

1. I have a git repo in a package called `foo` that I tagged it with `git tag -a 1.0.0`
2. I have added setuptools_scm and enabled it in `setup.py`. 
3. When I run `python setup.py sdist`, I get a tarball of version: `foo-1.0.1.dev39+ng14ecfe5`

There are 2 confusing bits:

**autoincrement**
the `1.0.1` is auto-incremented. I think this is expected behavior, but wanted to call it out anyway. I would have expected the distance and revision hash to be appended to the _last known_ version, rather than assuming that I'm working on the next patch version. (e.g. what if I'm really working on the next major or minor release?)

**`+ng<revision>`**
The docs say that the revision hash will be appended with `+n<revision>`, but I'm seeing that extra "g" character. 

Thanks for this project, I am very excited to stop trying to match tags to published version numbers!

**Comment by jaraco** [comment]
The auto-increment is indeed an intentional feature. It's there because the `.dev` suffix indicates a pre-release number, so it's necessary for the primary version to be incremented to _something_ for the .dev to work. It's conceivable that the bump for major or minor release could be inferred (there's a ticket requesting that based on branches and git flow), though no implementation. I believe there may also be parameters that would indicate which version to bump.

But now that you mention it, I think it's worth revisiting that design. Would it make more sense to just use the last tag and apply a .post<n>+n<hash>? Perhaps. It's possible the `.devN` scheme was an artifact of versioning implementations (hgtools, setuptoolshg) before [PEP 440](https://www.python.org/dev/peps/pep-0440) was drafted and the `.post` name was a suitable name. The main downside I see to using post-release indicators is that development releases will never have .dev in them... or there would need to be another signal to differentiate between post releases and dev pre-releases.

Regarding the second issue in this ticket, the g prefix comes from git and [is explained here](https://git-scm.com/docs/git-describe#_examples). Presumably you wouldn't get that character in the hash if you used another SCM. Should setuptools_scm omit that from the `describe` output? I think it adds value, especially since it has a documented purpose.

**Comment by mehulkar** [comment]
>  Would it make more sense to just use the last tag and apply a .post+n?

@jaraco yeah, I think that would make more sense to me as a new user. While scrounging around in the project, I did see the `post-release` option for `version_scheme`. I haven't tried it yet, but If it does what I think it does, i would expect it to be the default. (Totally not a big deal that it isn't though)

> the g prefix comes from git

ahh!!! Thanks for that reference. I was searching in the codebase for where that was being generated and neglected to look in the underlying `git describe` command (pretty cool, by the way, I had no idea that existed). Thanks for pointing it out.

> Should setuptools_scm omit that from the describe output?

I think it's fine to include it, but a note in the documentation would be useful, I think. Maybe just a note saying that under the hood, the version is coming from `git describe` would be useful?

**Comment by jaraco** [comment]
> Maybe just a note

Good idea. Could you send a PR?

**Comment by mehulkar** [comment]
happy to! submitted.

**Comment by sschuberth** [comment]
While it's true that the "g" prefix comes from `git describe`, IMO it's still very misleading to leave it in here. For consistency with other SCMs it should be so that everything after "n" is a valid commit identifier for the specific SCM. But if you leave the "g" in, it's not a valid commit identifier in Git! `git describe` adds the "g" to say "the following hash comes from **g**it", but if you already work with Git, the "g" must be dropped. In a way the `git describe`'s "g" is the equivalent to `setuptools_scm`'s "n", so it does not make sense to keep both.

If you do not want to remove it for backward compatibility, can we at least get a new `local_scheme` implementation that drops the "g"?

**Comment by RonnyPfannschmidt** [comment]
@sschuberth an bandaid scheme and a transition path for a next major version seem like a good combination, would you like to contribute that scheme
(the idea is to add a named scheme that people can use, and in the major version that fixes it, making it an alias for the normal scheme)

**Comment by jaraco** [comment]
I agree the `n` and `g` seem to be in conflict here, but maybe it's the n that should be dropped and not the g.

> but if you already work with Git, the "g" must be dropped

Well, that's not always the case. It's possible to for example use `hg-git` to checkout a git repo and cut a release of it in an untagged version, you'd get a Mercurial hash. I think it's a meaningful signal to indicate in which scm the hash was relevant.

I'd be more in favor of dropping the `n` and instead injecting a `h` or `m` (does convention suggest one or the other? [Linus suggests a full `hg`](http://git.661346.n2.nabble.com/meaning-of-quot-g-quot-in-git-describe-output-td4753369.html)) for Mercurial hashes.

meh. That's a mess.

Now I'm neither in favor nor against any changes. I withdraw my opinion.

**Comment by sschuberth** [comment]
> would you like to contribute that scheme

@RonnyPfannschmidt Well, I'm not only new to setuptools_scm, but also relatively new to Python in general, but I can try to find the time to give it a try...

> n that should be dropped and not the g.

@jaraco I was actually thinking about the same thing, but had similar scenarios in mind why this could become a mess. However, maybe instead of just "n" (What does that stand for anyway?) use a generic "scm"?

> Well, that's not always the case. It's possible to for example use hg-git to checkout a git repo

What I meant was "if you already work *locally* with Git". Like, `git log 14ecfe5` would work, whereas `git log g14ecfe5` (note the leading "g") would not.
