### ISSUE TITLE
Add an ability to install setuptools_scm-powered package without SCM

### ISSUE THREAD

**Issue by Kentzo** [pypa/setuptools-scm#162]
Using setuptools_scm breaks compatibility with "standard" workflow of installing or creating an sdist  when working with package outside of SCM (e.g. when it's downloaded as a ZIP archive from github).

**Comment by RonnyPfannschmidt** [comment]
@Kentzo as documented in https://github.com/pypa/setuptools_scm#notable-plugins there is setuptools_scm_github archive that enables partial support for that

full support can't be implemented with reasonable time/complexity cost,
since git is pretty much utterly hostile to something like this,
for mercurial archives this was implemented and possible since inception
(this is purely a shortcoming of git that the git developers don't want to fix)

using the `SETUPTOOLS_SCM_PRETEND_VERSION` environment variable ( https://github.com/pypa/setuptools_scm#environment-variables ) it is also possible to override this behavior

note that for real sdists (as made by `setup.py sdist`, setuptools_scm will include and use the correct metadata)

i strongly recommend automation of sdist uploads over relying on a tool as inferior as git

i am not opposed to someone else implementing extended metadata details in some way,
but personally i am not interested in spending volunteer time on it

**Comment by Kentzo** [comment]
@RonnyPfannschmidt I was rather thinking of plain archive with absolutely no SCM data.

Probably setuptools_scm could fall back to 0.0.0 when there is no version available anywhere?

**Comment by RonnyPfannschmidt** [comment]
@Kentzo this was the case and had been a disservice and breaker on regular basis, i'm very reluctant to add an opt-in for that since it does in fact break expectations,
so unless someone presents a really really good argument and a good implementation this wont happen

for custom use you can still implement a custom parse function and just return a normal version

**Comment by RonnyPfannschmidt** [comment]
@Kentzo also again, its not our job to fix the glaring and painful feature-holes of git if you used mercurial any sdist from the scm would work because mercurial adds correct metadata to the archives that is filesystem discover-able after unpacking

**Comment by Kentzo** [comment]
The error could be more user friendly. Something like.


setup.py is managed by the setuptools_scm package and it relies on SCM metadata for versioning. Unfortunately it was not found.
Ensure that you're installing from within SCM context or set version manually via `SETUPTOOLS_SCM_PRETEND_VERSION`.

**Comment by RonnyPfannschmidt** [comment]
@Kentzo in the context of installing from github&co that would generally imply putting wrong metadata into other packages as well (as soon as more than one setuptools_scm using package is involved)

the pretend_version env var is intended more for packagers that make distro packages, than for endusers,

**Comment by Kentzo** [comment]
I do not know how to properly handle this, but this case doesn't seem to be "rare".

My first encounter with `setuptools_scm` was through the python stack trace I got after trying to do `sdist install` from an archive I downloaded from github. And it was not pleasant :)

**Comment by RonnyPfannschmidt** [comment]
@Kentzo yes, but the message here is correct in telling people to go get a full repo because else they will get wrong metadata and it typically will bite them

**Comment by Kentzo** [comment]
@RonnyPfannschmidt Perhaps setuptools_scm should include a fallback to parse a file pointed by the user if nothing else can be found?

**Comment by anntzer** [comment]
FWIW I settled on
```
setup(
    ...
    **(dict(use_scm_version=lambda: ...)
       if subprocess.call("git rev-parse",
                          shell=True, stderr=subprocess.DEVNULL) == 0 else
       dict(version="a.b.c")),
)
```
which seems to work fine (adjust to your taste for older Pythons).  The use of `shell=True` ensures that call() returns nonzero, rather than raising a FileNotFoundError, in the case where git is not installed at all.
