### ISSUE TITLE
How do I use write_to with CI? 

### ISSUE THREAD

**Issue by zzztimbo** [pypa/setuptools-scm#313]
I'm creating my artifacts with `python setup.py sdist bdist_wheel` and utilizing write_to to write out a version.py file. I always end up with 'post0' and 'dirty' in my version. I would assume that using write_to would somehow ignore the file that was being written to.

**Comment by RonnyPfannschmidt** [comment]
@zzztimbo the write_to target file should be in a gitignore and not tracked in the scm
after all else invoking it is pretty much going to trigger a mess

**Comment by zzztimbo** [comment]
@RonnyPfannschmidt I literally figured out the necessity for gitignore minutes before I read your reply. Thank you!

**Comment by codejedi365** [comment]
I am having the same problem now a few years later but simply using a `.gitignore` does not solve the issue.  The new capabilities of dynamic configurations makes this issue more prevalent.

The new method in 2022 supports dynamic version determination through `pyproject.toml#project.dynamic = ["version"]`.  For my CI execution, this means when `python -m build` is executed the `sdist` created hooks `setuptools_scm` for the version (`setuptools_scm` is included in `pyproject.toml#build-system.requires`).  The prior command uses `semantic_release` to tag the version based on commit messages so when `setuptools_scm` runs during the artifact build process it causes an adjustment with a 0 suffix.  

My proposal: The `post0` or `dev0` I should automatically dropped because that means its on a current tag! I don't see a need of the `0` suffix and there is currently no option to completely remove any suffix based on the readme documentation.  All of the `version_scheme` values specify a suffix will be added.  The additional problem of this suffix is it is not fully conform to the `semver` standard so the `semver` compliant programs fail with it (I will add this as a separate issue).

For any others with this problem, I have found a janky solution.  Use `semantic_release print-version` to set the environment variable `SETUPTOOLS_SCM_PRETEND_VERSION` to render `setuptools_scm` inert while executing the `build` command. Although this works, I don't think it is a long-term solution to the problem.

Separately, I do concur with the above rationale that version files should not be committed to the repository and therefore gitignored.

**Comment by RonnyPfannschmidt** [comment]
@codejedi365 please open new issues instead of random posting in 4 year old closed issues

as for adding the dev/post 0 versions - this should only happens if the working tree is having changes (which points to a broken release process on your side)

so please open a new issue with enough details to understand whats broken

**Comment by codejedi365** [comment]
No need to be rude, I'm adhering to a different programmer etiquette than you desired.
