### ISSUE TITLE
Safe method for getting version from src without installing package?

### ISSUE THREAD

**Issue by Chris2048** [pypa/setuptools-scm#344]
The docs state: "It is discouraged to use setuptools_scm from sphinx itself", and instead describe using pkg_resources to get version from the package.

But, in my case I'm trying to avoid installing the package as this brings in the package plus all its deps, just for the sake of a version number (for sphinx docs).

The src code for the package is available, so version is available in version.py per

> use_scm_version={"write_to": ...

Is there a safe way of getting it directly from here?

**Comment by RonnyPfannschmidt** [comment]
its my understanding that or generating sphinx docs that use actual parts of the package, you need the package in a importable state anyway, so if thee importable state doesnt actually require the dependencies, but has the version, then just import it

otherwise it may be perfectly reasonable to use a get_version call from the documentation,
its important to configure it correctly for working even from a sdist, i havent gotten around at collecting the subtle details of such a use-case

**Comment by RonnyPfannschmidt** [comment]
closing as i believe this was q question that was answered sufficiently
