### ISSUE TITLE
document painless git usage in buildkit docker usage

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pypa/setuptools-scm#568]
For future reference (building only works in recent docker versions with buildkit support) you can avoid having `.git` in one of your layers by temporarily bind-mounting it during build time [[docs]](https://github.com/moby/buildkit/blob/v0.8.3/frontend/dockerfile/docs/syntax.md):

```dockerfile
RUN --mount=source=.git,target=.git,type=bind \
    pip install --no-cache-dir -e .
```

_Originally posted by @ddelange in https://github.com/pypa/setuptools_scm/issues/77#issuecomment-844927695_

**Comment by ddelange** [comment]
### problem
I just noticed that the above command will produce a guess-next-dev-like output in the image, despite being on a clean tag:
```
version = "0.4.14.dev0+g102e58c.d20210520"
```

### cause
because I didn't copy all the tracked files into the docker image, there are some missing files for git and the `git describe` command in `cli.py` will add a `-dirty` postfix (although I'm actually on a tag, not dirty):
```console
$ # on host machine 
$ git describe --dirty --tags --long --match *[0-9]*
0.4.13-0-g102e58c

$ # inside the pod, with a post mortem bind mount `docker run -v /.../.git:/.../.git ...`
$ git describe --dirty --tags --long --match *[0-9]*
0.4.13-0-g102e58c-dirty
```

### solution
As I'm only building docker images from tags, for my use case I could get the desired outcome
```
version = "0.4.13"
```
 by patching `setup.py`, removing `--dirty` from the command:
```py
use_scm_version={"git_describe_command": "git describe --tags --long --match *[0-9]*"}
```

Not an ideal solution for people who want to build dirty docker images and have `+dirty` reflected in the resulting container (_why didn't it wrongly show `+dirty` in the first code snippet above by the way?_), but for my use case this is an acceptable patch.
