### ISSUE TITLE
Get alias

### ISSUE THREAD

**Issue by tdegeus** [pypa/setuptools-scm#645]
After I tag a commit the version will change. Now my question: can I get the "alias", e.g. between "5.0" and "4.1.dev1+g423e6a8" ?

**Comment by RonnyPfannschmidt** [comment]
i don't follow completely

typically when the next auto-generated version does not match, one can uzse a `dev` tag to start a new line of development

so [the version schemes](https://github.com/pypa/setuptools_scm#version-number-construction) have a option to tag a dev version for something specific

so if you run git tag `v5.0.dev0` then any commit after that will be tagged as `5.0.devN`

pytest jsut recently did that for the `7.0` series - https://github.com/pytest-dev/pytest/releases/tag/7.0.0.dev0

**Comment by tdegeus** [comment]
I should clarify. What happened is that I generated some output with my last committed state, and I encoded the version in the output ("4.1.dev1+g423e6a8"). I then looked at the output and realised that I was satisfied to tag that precise commit as "5.0" (and run some more simulations). However, I wanted to unify the version stored in all output, as "4.1.dev1+g423e6a8" now has the right to be called "5.0" (which was encoded in the rest of simulations). 

Now it is of course possible to search if a tag exists with `g423e6a8` (for example with GitPython), however, I wanted to stick with a single library only.

**Comment by RonnyPfannschmidt** [comment]
Typically due to the usually relative cost of generating outputs for python, vs the complexity of the aliasing people just generate a new output from the tag

This is the first time i get a request to alias prior development versions to the tag

I currently don't see enough value in this to implement correctly

And I don't see how one would use it in practice

Please provide some examples that enable other people to understand what you want to archive

**Comment by RonnyPfannschmidt** [comment]
closing due to lack of follow up
