### ISSUE TITLE
SETUPTOOLS_SCM_PRETEND_VERSION_FOR_DIST_NAME should escape hyphens

### ISSUE THREAD

**Issue by CarlosRDomin** [pypa/setuptools-scm#829]
While it is great being able to override SETUPTOOLS_SCM_PRETEND_VERSION for a particular distribution (e.g. working on a CI that doesn't clone full `.git` history or remotely developing inside a docker container through ssh), it currently has an inconvenience: setting the environment variable will likely not be shell-compliant, as most python package names contain dashes/hyphens, and those are not allowed. For instance, if your package is called `hello-world`, the following would not work:
```sh
export SETUPTOOLS_SCM_PRETEND_VERSION_FOR_HELLO-WORLD=1.2.3
# bash: export: `SETUPTOOLS_SCM_PRETEND_VERSION_FOR_HELLO-WORLD=1.2.3': not a valid identifier
```
whereas with
```sh
export SETUPTOOLS_SCM_PRETEND_VERSION_FOR_HELLO_WORLD=1.2.3
pip install .
```
the override gets ignored.

The only workaround I've found is using the following syntax:
```sh
env 'SETUPTOOLS_SCM_PRETEND_VERSION_FOR_HELLO-WORLD=1.2.3' pip install .
```
but it isn't a great user experience, especially since it can't easily be set externally.

Intuitively, it seems like the fix would be to simply replace `dist_name.upper()` in https://github.com/pypa/setuptools_scm/blob/main/src/setuptools_scm/_overrides.py#L19 with `dist_name.upper().replace("-", "_")`

**Comment by RonnyPfannschmidt** [comment]
Good point, thanks

**Comment by nitzmahone** [comment]
Yeah, just tripped over this one this week on `ansible-builder` and `ansible-runner` - pesky dash-named dists... :laughing: I wasn't surprised when it failed, since the PEP503 (and other related) normalizations are so inconsistently applied across the packaging ecosystem with specific needs that have evolved over time.

It seems like at least for current fully-supported Pythons, the "best" stdlib-available implementation that would work out of the box is in [importlib-metadata's `Prepared(distname).normalized`](https://github.com/python/importlib_metadata/blob/705a7571ec7c5abec4d4b008da3a58df7e5c94e7/importlib_metadata/__init__.py#L769-L774), but even though that looks like public API, it feels "icky" to call it - I wish it was exposed and maintained somewhere as a proper "normalize dist name" utility method.

I see that this project already relies on the `importlib_metadata` backport for Python 3.7- if it were to delegate name normalization to `importlib.metadata.Prepared(distname).normalized`, the declared `importlib_metadata` backport dep would need a minimum version of 3.1.0 to get the current normalization of "single-case and convert all internal `.` `-` to `_`".

I might throw together a fix, although our need for it under normal circumstances has almost completely evaporated with the `.git_archival.txt` stuff, so thanks a million to whoever implemented that!

**Comment by RonnyPfannschmidt** [comment]
I absolutely welcome enhancements there, but I have a slightly large Mr that touches some of the bits there

I'll elaborate later tonight
